api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        pagination_items_per_page: 10
        formats:
            jsonld: [ 'application/ld+json' ]
            json: [ 'application/json' ]
            html: [ 'text/html' ]
    keep_legacy_inflector: false
    use_symfony_listeners: true
